---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcloud-export-example
spec:
  schedule: "@midnight"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
        spec:
          restartPolicy: Never
          containers:
          - name: gcloud-sql-export
            image: mintel/k8s-gcloud-export:initial
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /sa/credentials.json
            - name: GOOGLE_SQL_INSTANCE_NAME
              value: my-db-instance-name
            - name: GOOGLE_SQL_BACKUP_BUCKET
              value: my-backup-bucket-name
            - name: GOOGLE_SQL_BACKUP_BUCKET_PATH
              value: some-folder/some-sub-folder
            - name: DATABASE 
              value: my-database
            - name: BACKUP_SCHEDULE
              value: none
            resources:
              limits:
                cpu: 200m
                memory: 64Mi
              requests:
                cpu: 100m
                memory: 32Mi
            volumeMounts:
            - name: gcloud-export-sa
              mountPath: /sa
            - name: gcloud-config
              mountPath: /.config
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 65534
          volumes:
          - name: gcloud-export-sa
            secret:
              secretName: gcloud-export-sa
          - name: gcloud-config
            emptyDir: {}
